Loppuprojekti_MVC/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Loppuprojekti_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Threading;
using Microsoft.AspNetCore.Mvc.Localization;

namespace Loppuprojekti_MVC.Controllers
{
    public class CountryController : Controller
    {
        private CountryUtil ct = new CountryUtil();

        //TODO: Change name to Index, also correct all references elsewhere..
        // GET: Country/CountryIndex
        public ActionResult CountryIndex(string firstLetter = "a")
        {
            CultureInfo cultureInfo = new CultureInfo("fi-FI");
            firstLetter = firstLetter.ToLower();
            List<CountryList> ctrs = ct.Countries().Where(t => t.Country.ToLower().StartsWith(firstLetter)).OrderBy(c => c.Country).ToList();

            ViewBag.Letters = string.Join("", ct.Countries().OrderBy(t => t.Country).Select(t => t.Country.Substring(0, 1)).Distinct());
            return View(ctrs);
        }

        public ActionResult Country(string country) 
        {
            RegionInfo myRI = new RegionInfo(country);
            CountryUtil cu = new CountryUtil();
            IndividualSpecies ind = new IndividualSpecies();
            var countryspecies = cu.Country(country);
            var allThreatenedSpecies = cu.Country(country).Where(c => c.Category == "EN" || c.Category == "EX" || c.Category == "EW"
            || c.Category == "CR" || c.Category == "VU");
            ViewBag.C = myRI.EnglishName;
            ViewBag.RI = myRI;
            ViewBag.Categories = string.Join("", ind.Category);
            RestUtil ru = new RestUtil();

            //TODO: Upload common names to a json from which to query
            //foreach (var item in allThreatenedSpecies)
            //{
            //    //string name = ru.SingleSpecies(item.ScientificName).FirstOrDefault()?.MainCommonName;
            //    string name = ru.SingleSpecies(item.ScientificName).FirstOrDefault()?.MainCommonName;
            //    item.CommonName = name;
            //}

            return View(allThreatenedSpecies); // check what we actually want here!!
        }

        //TODO: Combine these methods & their Views, unnessary code doubling. 

        public ActionResult ENSpecies(string country)
        {
            RegionInfo myRI = new RegionInfo(country);
            CountryUtil cu = new CountryUtil();
            var endangeredSpecies = cu.Country(country).Where(c => c.Category == "EN");
            ViewBag.C = myRI.EnglishName;
            ViewBag.EN = endangeredSpecies;
            return View(endangeredSpecies);
        }

        public ActionResult EXSpecies(string country)
        {
            RegionInfo myRI = new RegionInfo(country);
            CountryUtil cu = new CountryUtil();
            var extinctSpecies = cu.Country(country).Where(c => c.Category == "EX");
            ViewBag.C = myRI.EnglishName;
            return View(extinctSpecies);
        }

        public ActionResult EWSpecies(string country)
        {
            RegionInfo myRI = new RegionInfo(country);
            CountryUtil cu = new CountryUtil();
            var extinctWildSpecies = cu.Country(country).Where(c => c.Category == "EW");
            ViewBag.C = myRI.EnglishName;
            return View(extinctWildSpecies);
        }

        public ActionResult CRSpecies(string country)
        {
            RegionInfo myRI = new RegionInfo(country);
            CountryUtil cu = new CountryUtil();
            var criticallyEndangeredSpecies = cu.Country(country).Where(c => c.Category == "CR");
            ViewBag.C = myRI.EnglishName;
            return View(criticallyEndangeredSpecies);
        }

        public ActionResult VUSpecies(string country)
        {
            RegionInfo myRI = new RegionInfo(country);
            CountryUtil cu = new CountryUtil();
            var vulnerableSpecies = cu.Country(country).Where(c => c.Category == "VU");
            ViewBag.C = myRI.EnglishName;
            return View(vulnerableSpecies);
        }

        //GET countries working version
        //public ActionResult CountryIndex(/*string firstLetter="a"*/)
        //{
        //    CountryUtil ct = new CountryUtil();
        //    //firstLetter = firstLetter.ToLower();
        //    //List<CountryList> countries = ct.Countries
        //    var countries = ct.Countries();
        //    return View(countries);
        //}


    }
}

Loppuprojekti_MVC/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Loppuprojekti_MVC.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome(string name, int ID=1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["ID"] = ID;
            return View();
        }

    }
}

Loppuprojekti_MVC/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Loppuprojekti_MVC.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index(string searchTerms)
        {
            if (string.IsNullOrEmpty(searchTerms))
            {
                return View();
            }
            else
            {
                return RedirectToAction("SingleSpecies", "Species", new { @searchTerms = searchTerms });
            }

        }

        // GET: Search/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Search/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Search/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Search/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Search/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Loppuprojekti_MVC/Views/Shared/_CommonNamePartial.cshtml
@model Loppuprojekti_MVC.Models.SpeciesCommonName

@Html.DisplayNameFor(model => model.MainCommonName)
@Html.DisplayFor(model => model.MainCommonName)

Loppuprojekti_MVC/Views/Shared/_FooterLinks.cshtml
<div>Data is loaded from IUCN RedList -REST API: <i>IUCN 2018. IUCN Red List of Threatened Species. Version 2018-2</i> <www.iucnredlist.org></div>
<br />
<ul class="list-group">
    <li class="list-group-item"><a href="https://www.iucnredlist.org/">IUCN RED LIST website</a></li>
    <li class="list-group-item"><a href="https://www.gbif.org/">Global Biodiversity Information Facility - Free and open Access Biodiversity Data</a></li>
    <li class="list-group-item"><a href="http://www.sciname.info/">SciName Finder</a></li>
    <li class="list-group-item"><a href="https://laji.fi/">Suomen lajitietokeskus </a></li>
    <li class="list-group-item"><a href="http://www.luomus.fi/fi">Luonnontieteellinen keskusmuseo</a></li>
</ul>

Loppuprojekti_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Endangered Planet</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- Syncfusion Essential JS 2 Styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <a class="navbar-brand" asp-controller="Default" asp-action="Index">Endangered Planet</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Country" asp-action="CountryIndex">Countries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Species" asp-action="SpeciesIndex">Species</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Resources" asp-action="ResourcesIndex">Resources</a>
                </li>
            </ul>
            @*<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>*@
        </div>
    </nav>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*<br />
                Data is loaded from IUCN RedList -REST API: <i>IUCN 2018. IUCN Red List of Threatened Species. Version 2018-2</i> <www.iucnredlist.org>
                <br />*@
            &copy; 2020
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>